"""empty message

Revision ID: 3d74ba988ad8
Revises: 
Create Date: 2018-08-09 22:33:02.311233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d74ba988ad8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.String(length=100), nullable=False),
    sa.Column('followed_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['front_user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['front_user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('bookmark',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['front_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.drop_table('cms_user_detail')
    op.create_foreign_key(None, 'cms_role_user', 'cms_user', ['cms_user_id'], ['id'])
    op.create_foreign_key(None, 'cms_role_user', 'cms_role', ['cms_role_id'], ['id'])
    op.add_column('cms_user', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('cms_user', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('cms_user', sa.Column('gender', sa.Integer(), nullable=True))
    op.add_column('cms_user', sa.Column('intro', sa.Text(), nullable=True))
    op.add_column('cms_user', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('cms_user', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('comment', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'comment', 'front_user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.add_column('front_user', sa.Column('confirm', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'highlight_post', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'post', 'front_user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'post', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'highlight_post', type_='foreignkey')
    op.drop_column('front_user', 'confirm')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'disabled')
    op.drop_column('cms_user', 'phone')
    op.drop_column('cms_user', 'name')
    op.drop_column('cms_user', 'intro')
    op.drop_column('cms_user', 'gender')
    op.drop_column('cms_user', 'birthday')
    op.drop_column('cms_user', 'avatar')
    op.drop_constraint(None, 'cms_role_user', type_='foreignkey')
    op.drop_constraint(None, 'cms_role_user', type_='foreignkey')
    op.create_table('cms_user_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('uid', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('gender', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('intro', mysql.TEXT(), nullable=True),
    sa.Column('_avatar', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.drop_table('bookmark')
    op.drop_table('follows')
    # ### end Alembic commands ###
